[package]
name = "release/preloader-module"
version = "1.0.5"
registry = "https://github.com/Rivrs-Roblox/wally-index"
realm = "shared"

[dependencies]
knit = "sleitnick/knit@1.5.1"
signal = "sleitnick/signal@2.0.1"
core = "release/core-module@^1"
